apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
    tag: latest
  name: techtrends
  namespace: sandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: techtrends
      tag: latest
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
        tag: latest
    spec:
      containers:
      - image: hermien/techtrends:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        name: techtrends
        ports:
        - containerPort: 3111
          name: techtrends
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3111
          failureThreshold: 1
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healtz
            port: 3111
          initialDelaySeconds: 5
          periodSeconds: 5

